version: "3"

services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    container_name: investo_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data



  api:
    build: .
    container_name: investo_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db


  volumes:
  postgres_data:

